[workspace]
members = [".", "crates/app", "crates/config", "crates/foundry", "crates/ui", "crates/itest"]
resolver = "2"

[workspace.package]
version = "0.0.4"
edition = "2021"
license = "MIT"
rust-version = "1.80"

[workspace.dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["clock", "serde"] }
crossterm = "0.27"
dirs = "5.0"
ratatui = "0.26.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.39", features = ["macros", "process", "rt-multi-thread", "sync", "time", "io-util"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
indexmap = "=2.7.0"

[package]
name = "foundry-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Feature-rich, keyboard-first TUI for Foundry users"
documentation = "https://github.com/KanishkKhurana/foundry-tui/blob/main/README.md"
repository = "https://github.com/KanishkKhurana/foundry-tui"
homepage = "https://github.com/KanishkKhurana/foundry-tui"
readme = "README.md"
keywords = ["foundry", "forge", "tui", "solidity", "ethereum"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
indexmap.workspace = true
foundry-tui-app = { version = "0.0.4", path = "crates/app" }
foundry-tui-config = { version = "0.0.4", path = "crates/config" }
foundry-tui-foundry = { version = "0.0.4", path = "crates/foundry" }
foundry-tui-ui = { version = "0.0.4", path = "crates/ui" }
