[package]
name = "foundry-tui-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Ratatui rendering and interaction layer for foundry-tui"
documentation = "https://github.com/KanishkKhurana/foundry-tui/blob/main/crates/ui/README.md"
repository = "https://github.com/KanishkKhurana/foundry-tui"
homepage = "https://github.com/KanishkKhurana/foundry-tui"
readme = "README.md"
keywords = ["foundry", "tui", "ratatui", "solidity"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow.workspace = true
chrono.workspace = true
crossterm.workspace = true
ratatui.workspace = true
unicode-segmentation = "=1.12.0"
foundry-tui-app = { version = "0.0.4", path = "../app" }
foundry-tui-config = { version = "0.0.4", path = "../config" }
foundry-tui-foundry = { version = "0.0.4", path = "../foundry" }
